apiVersion: v1
kind: Service
metadata:
  name: {{ include "wonderlust.fullname" . }}-frontend
  labels:
    {{- include "wonderlust.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "wonderlust.name" . }}-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
