apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wonderlust.fullname" . }}-secrets
  labels:
    {{- include "wonderlust.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.googleClientId | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleClientSecret | quote }}
