apiVersion: v1
kind: Service
metadata:
  name: wonderlust-backend
  namespace: wonderlust
  labels:
    app.kubernetes.io/name: wonderlust-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: wonderlust
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: wonderlust-backend
