apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: wonderlust-backend-hpa
  namespace: wonderlust
  labels:
    app.kubernetes.io/name: wonderlust-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wonderlust-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: wonderlust-frontend-hpa
  namespace: wonderlust
  labels:
    app.kubernetes.io/name: wonderlust-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wonderlust-frontend
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
