apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wonderlust-ingress
  namespace: wonderlust
  labels:
    app.kubernetes.io/name: wonderlust
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: wonderlust-backend
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wonderlust-frontend
                port:
                  number: 80
