apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wonderlust

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mongodb.yaml
  - redis.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
  - hpa.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: wonderlust
      app.kubernetes.io/managed-by: kustomize
