apiVersion: v1
kind: Secret
metadata:
  name: wonderlust-secrets
  namespace: wonderlust
  labels:
    app.kubernetes.io/name: wonderlust
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  JWT_SECRET: "wonderlust_super_secure_jwt_secret_devops_key_2026"
  GOOGLE_CLIENT_ID: "sample_google_client_id"
  GOOGLE_CLIENT_SECRET: "sample_google_client_secret"
